### ISSUE TITLE
Configuration error on composer require

### ISSUE THREAD

**Issue by enekochan** [Simply-Stream/TwitchApiBundle#9]
When installing with composer require it always gives an error because the configuration has not yet been done for the bundle.

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 233:
!!                                                                                 
!!    The child config "twitch_id" under "simplystream_twitch_api" must be config  
!!    ured.                                                                        
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

```

This could be avoided now using Flex recipes. It's just a matter of adding the creation of the appropriate config file with env variables in the symfony/recipes-contrib repo.  This is an example that could be helpfull to use as base:

https://github.com/symfony/recipes-contrib/tree/main/velhron/dadata-bundle/1.0

**Comment by enekochan** [comment]
I think this could be more or less the content of the recipe.

`manifest.json`:

```yaml
{
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    },
    "env": {
        "TWITCH_ID": "",
        "TWITCH_SECRET": "",
        "TWITCH_REDIRECT_URI": "",
        "TWITCH_WEBHOOK_SECRET": ""
    }
}
```

`config/packages/simplystream_twitch_api.yaml`:

```yaml
simplystream_twitch_api:
    twitch_id: '%env(TWITCH_ID)%'
    twitch_secret: '%env(TWITCH_SECRET)%'
    redirect_uri: '%env(TWITCH_REDIRECT_URI)%'
    webhook:
        secret: '%env(TWITCH_WEBHOOK_SECRET)%'
```
